# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
      - name: Install dependencies
        run: flutter pub get
      - name: Format code
        run: dart format --fix .
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Publish
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutter: true
          force: true